name: MDGitView
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    macOS: "14.0"
settings:
  base:
    SWIFT_VERSION: 5.10
    MARKETING_VERSION: 0.5.0
    CURRENT_PROJECT_VERSION: 6
    DEVELOPMENT_TEAM: 8C2T254JY2
    CODE_SIGN_STYLE: Automatic
targets:
  MDGitView:
    type: application
    platform: macOS
    info:
      path: Config/MDViewer-Info.plist
      properties:
        CFBundleDocumentTypes:
          - CFBundleTypeName: Markdown Document
            CFBundleTypeRole: Viewer
            LSHandlerRank: Owner
            LSItemContentTypes:
              - net.daringfireball.markdown
            CFBundleTypeExtensions:
              - md
              - markdown
              - mdown
              - mkd
              - mkdn
        NSHumanReadableCopyright: "Copyright 2026 Toni Hintikka. All rights reserved."
        UTImportedTypeDeclarations:
          - UTTypeIdentifier: net.daringfireball.markdown
            UTTypeDescription: Markdown Document
            UTTypeConformsTo:
              - public.plain-text
            UTTypeTagSpecification:
              public.filename-extension:
                - md
                - markdown
                - mdown
                - mkd
                - mkdn
    entitlements:
      path: Config/MDViewer.entitlements
    sources:
      - path: App
      - path: Shared
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.toni.mdgitview
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "$(SRCROOT)/Vendor/libmd_ffi.a"
        LIBRARY_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/Vendor"
        HEADER_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/../md-ffi/include"
    preBuildScripts:
      - name: Build Rust FFI
        script: |
          if [ -x "${SRCROOT}/../scripts/build_rust.sh" ]; then
            "${SRCROOT}/../scripts/build_rust.sh" "${CONFIGURATION}"
          else
            echo "warning: scripts/build_rust.sh not found"
          fi
    dependencies:
      - target: MarkdownPreviewExtension
        embed: true
      - target: MarkdownThumbnailExtension
        embed: true

  MarkdownPreviewExtension:
    type: app-extension
    platform: macOS
    info:
      path: Config/MarkdownPreviewExtension-Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.quicklook.preview
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).MarkdownPreviewProvider"
          NSExtensionAttributes:
            QLIsDataBasedPreview: true
            QLSupportedContentTypes:
              - net.daringfireball.markdown
            QLSupportsSearchableItems: false
    entitlements:
      path: Config/MarkdownPreviewExtension.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
        com.apple.security.files.user-selected.read-only: true
        com.apple.security.temporary-exception.files.absolute-path.read-only:
          - /
    sources:
      - path: PreviewExtension
      - path: Shared
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.toni.mdgitview.preview
        ENABLE_HARDENED_RUNTIME: YES
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "$(SRCROOT)/Vendor/libmd_ffi.a"
        LIBRARY_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/Vendor"

  MarkdownThumbnailExtension:
    type: app-extension
    platform: macOS
    info:
      path: Config/MarkdownThumbnailExtension-Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.quicklook.thumbnail
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).MarkdownThumbnailProvider"
          NSExtensionAttributes:
            QLSupportedContentTypes:
              - net.daringfireball.markdown
    entitlements:
      path: Config/MarkdownThumbnailExtension.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
    sources:
      - path: ThumbnailExtension
      - path: Shared
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.toni.mdgitview.thumbnail
        ENABLE_HARDENED_RUNTIME: YES
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "$(SRCROOT)/Vendor/libmd_ffi.a"
        LIBRARY_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/Vendor"
